server:
  port: 8080

spring:
  application:
    api-prefix: ${API_PREFIX:/api/v1}
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/bookstore_db?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.MySQL8Dialect

  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher

  devtools:
    restart:
      enabled: true
    livereload:
      enabled: true
  jwt:
    signerKey: "1TjXchw5FloESb63Kc+DFhTARvpWL4jUGCwfGWxuG5SIf/1y/LgJxHnMqaF6A/ij"
    valid-duration: 1800000
    refreshable-duration: 604800

  cloudinary:
    cloudinary.cloud_name: "dzvxgyg88"
    cloudinary.api_key: "281855212738654"
    cloudinary.api_secret: "CBx98FIol43xihZJt0fX1AKgt9E"

logging:
  level:
    org.springframework: INFO
    org.hibernate.SQL: DEBUG
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE

gemini:
  api-key: "AIzaSyCxiDbi7JbHV1SchJRrEx-5FgIz8dbScks"
  base-url: https://generativelanguage.googleapis.com/v1beta/models/gemini-2.0-flash:generateContent
  max-output-tokens: 1000
  temperature: 0.1
  top-p: 0.8
  top-k: 10
  max-history-size: 20
payment:
  vnPay:
    url: ${PAY_URL:https://sandbox.vnpayment.vn/paymentv2/vpcpay.html}
    tmnCode: ${TMN_CODE:58X4B4HP}
    secretKey: ${SECRET_KEY:VRLDWNVWDNPCOEPBZUTWSEDQAGXJCNGZ}
    returnUrl: ${RETURN_URL:http://localhost:3000/payment/callback}
    version: ${VERSION:2.1.0}
    command: ${COMMAND:pay}
    orderType: ${ORDER_TYPE:other}
